#include <biovoltron/file_io/fasta.hpp>
#include <catch.hpp>
#include <filesystem>
#include <fstream>
#include <ranges>
#include <sstream>

using namespace biovoltron;
using namespace std::string_literals;

const auto data_path = std::filesystem::path{DATA_PATH};

inline void
CHECK_FILE_IDENTITY(const std::filesystem::path& path,
                    std::string_view expected_result, bool is_fastq) {
  std::fstream fin(path, std::ios::in);
  REQUIRE(fin.is_open() == true);
  std::ostringstream oss;
  if (is_fastq) {
    std::vector<FastqRecord<>> Records;
    FastqRecord record;
    while (fin >> record) Records.emplace_back(record);
    for (auto record : Records) oss << record << '\n';
  } else {
    std::vector<FastaRecord<>> Records;
    FastaRecord record;
    while (fin >> record) Records.emplace_back(record);
    for (auto record : Records) oss << record << '\n';
  }
  REQUIRE(oss.str() == expected_result);
}

TEST_CASE("Fastq basic I/O") {
  SECTION("Single record") {
    FastqRecord record;

    std::istringstream iss{R"(@SRR001666.1
GGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9IC
)"};

    std::ostringstream oss;

    while (iss >> record) oss << record << '\n';

    REQUIRE(record.name == "SRR001666.1");
    REQUIRE(record.seq == "GGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACC");
    REQUIRE(record.qual == "IIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9IC");
  }

  SECTION("Multiple records") {
    FastqRecord record1, record2, record3, record4;

    std::istringstream iss{R"(@alpha1 comm
AAAAAAAAA
+
IIIIIIIII
@alpha2 comm
TTTTTTTTT
+
IIIIIIIII
@alpha3 comm
CCCCCCCCC
+
IIIIIIIII
@alpha4 comm
GGGGGGGGG
+
IIIIIIIII


)"};

    iss >> record1 >> record2 >> record3 >> record4;

    REQUIRE(record1.name == "alpha1");
    REQUIRE(record1.seq == "AAAAAAAAA");
    REQUIRE(record1.qual == "IIIIIIIII");

    REQUIRE(record2.name == "alpha2");
    REQUIRE(record2.seq == "TTTTTTTTT");
    REQUIRE(record2.qual == "IIIIIIIII");

    REQUIRE(record3.name == "alpha3");
    REQUIRE(record3.seq == "CCCCCCCCC");
    REQUIRE(record3.qual == "IIIIIIIII");

    REQUIRE(record4.name == "alpha4");
    REQUIRE(record4.seq == "GGGGGGGGG");
    REQUIRE(record4.qual == "IIIIIIIII");
  }

  SECTION("SHORTQUALITY.FASTQ") {
    std::istringstream iss{R"(@SEQ1
ACfTACGTACGTAGCTGATCGATCGTACGTAGCTGACA
+
SHORTQUALITY:)
@SEQ2
NNNNNCGTACGTAGCTGATCGATCGTACGTAGCTGACA
+
!!!!!AIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII)"};

    FastqRecord record1, record2;
    while (iss >> record1 >> record2)
      ;
    REQUIRE(record1.name == "SEQ1");
    REQUIRE(record1.seq == "ACfTACGTACGTAGCTGATCGATCGTACGTAGCTGACA");
    REQUIRE(record1.qual == "SHORTQUALITY:)");

    REQUIRE(record2.name == "SEQ2");
    REQUIRE(record2.seq == "NNNNNCGTACGTAGCTGATCGATCGTACGTAGCTGACA");
    REQUIRE(record2.qual == "!!!!!AIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII");
  }

  SECTION("OLD_SANGER.FASTQ") {
    std::istringstream iss{R"(@SANGER_FASTQ
ACGTGCTAGCTAGCTGATCGTACGTAGCTGACT
ACGTGCTAGCTAGCTGATCGTACGTAGCTGACT
ACGTGCTAGCTAGCTGATCGTACGTAGCTGACT
ACGTGCTAGCTAGCTGATCGTACGTAGCTGACT
+
999999999999999897989999999989889
999664999999999897989999999989889
999999199999999897989999999989889
999999911999999897989999999989889)"};

    FastqRecord record;

    while (iss >> record)
      ;

    REQUIRE(record.name == "SANGER_FASTQ");
    REQUIRE(
        record.seq ==
        "ACGTGCTAGCTAGCTGATCGTACGTAGCTGACTACGTGCTAGCTAGCTGATCGTACGTAGCTGACTACGT"
        "GCTAGCTAGCTGATCGTACGTAGCTGACTACGTGCTAGCTAGCTGATCGTACGTAGCTGACT");
    REQUIRE(
        record.qual ==
        "9999999999999998979899999999898899996649999999998979899999999898899999"
        "99199999999897989999999989889999999911999999897989999999989889");
  }
}

TEST_CASE("FASTQ FILE I/O") {
  SECTION("READFILE1.FASTQ") {
    std::string_view expected_result{R"(@A00709:43:HYG25DSXX:1:1101:3640:1000
GCATTCACCCTGGTCGGGTCGGCGTTGTAATCTGCCTGGACCAGACTACGCACTGTCGGTGGGGTGGCGGCGCGGGAAACGTCATGTCGC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:6189:1000
TCGGAACCTCGTCCACGATTTGCGGAGCCGCGTTCGCGACCAGGCGGTCCTTGCCCACCAACTGCAGGGTCATCAAGTAGCCCCCGGGGC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFF:FFFFFFFFFFFFFFFFFFFFF,FFFFFFF
@A00709:43:HYG25DSXX:1:1101:10818:1000
CCAACAATGCTTACGTTCACACCCAACGCCCGAACCCTATGACGGTAGGCAAGTTAAGGCGGGCTTTTTTGCGGATTTACGTAAAGCGGC
+
FFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFF:F:FF,FFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFF:FF::F:FFF,F:FFFFFF
@A00709:43:HYG25DSXX:1:1101:14705:1000
GTTGTGCCGGTAATAACATTTGTTATTGAGAGGGCCCTCCTGCGATTGGCTTGATGGTTCCGTAAGTGTGAAATGTCACTCCGTTATCGA
+
FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:14814:1000
ATCGTAGGCAAAAGTTCCAACAAGATCTGTTGTCCCGCCGTCTGTCCCAAGGGGATTAACTTCACCCCCGCCCCAATTAAATTGCTCGCC
+
FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:15935:1000
CTCTTCCTTGTCGGCGGTGGAGAAGCAGAGGCAGAAAAGGTCGCGCTCGTAGGGGATGCCGTCCTCGATCGCCAGACGCTCGCTGGCGCG
+
FFFFF,FFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFF,FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:17960:1000
CCCGCACGCGGATGTTCGGATGGTTCCGCACGGCCTCGCTGAGGGCGGTCTGGATCACCAATCCGGTGGCGTCCTTGGCGTGGTAGATGC
+
FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:
)"};
    CHECK_FILE_IDENTITY(data_path / "test1.fastq", expected_result, true);
  }

  SECTION("READFILE2.FASTQ") {
    std::string_view expected_result{R"(@SEQ1
ACGTACGTACGTAGCTGATCGATCGTACGTAGCTGACA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ2
NNNNNCGTACGTAGCTGATCGATCGTACGTAGCTGACA
+
!!!!!AIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ3
ACGTACGTACGTAGCTGATCGATCGTACGTAGCTGACN
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
)"};
    CHECK_FILE_IDENTITY(data_path / "test2.fastq", expected_result, true);
  }

  SECTION("READFILE3.FASTQ") {
    std::string_view expected_result{R"(@A00709:43:HYG25DSXX:1:1101:3640:1000
GCATTCACCCTGGTCGGGTCGGCGTTGTAATCTGCCTGGACCAGACTACGCACTGTCGGTGGGGTGGCGGCGCGGGAAACGTCATGTCGC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:3640:1000
ACCACGACTTACGTGGATGGCAATGTGACGGTCGGAACCGAATACGAATATCGCGTGGAGCGCACGGGGTCGTCCTTCGACGGAAATGCC
+
FFF:FFFFFFFF:FFFFF:FFFFFFFFFFFF:FFFFFFFFFFFFFF:FFF,FFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFFFF
@A00709:43:HYG25DSXX:1:1101:6189:1000
TCGGAACCTCGTCCACGATTTGCGGAGCCGCGTTCGCGACCAGGCGGTCCTTGCCCACCAACTGCAGGGTCATCAAGTAGCCCCCGGGGC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFF:FFFFFFFFFFFFFFFFFFFFF,FFFFFFF
@A00709:43:HYG25DSXX:1:1101:6189:1000
TCGACGCGGTCGCTAAGTTCACAGATGCCGTTCAGATGGACATCGCCGTGCGGTTGTCCCTTACGCCCGACGACCCAGGTGCGGTCTCGC
+
FFFFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFFF:FFFFFFF
@A00709:43:HYG25DSXX:1:1101:10818:1000
CCAACAATGCTTACGTTCACACCCAACGCCCGAACCCTATGACGGTAGGCAAGTTAAGGCGGGCTTTTTTGCGGATTTACGTAAAGCGGC
+
FFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFF:F:FF,FFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFF:FF::F:FFF,F:FFFFFF
@A00709:43:HYG25DSXX:1:1101:10818:1000
CGCCAAAGGCGCGCCGCAGCGACCGATGCACAGCGGCCCGCGCTCCGACGCGCCGCCCAGAGGCCCACGGGGACCGCGCGGCCCGGGCAA
+
FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:14705:1000
GTTGTGCCGGTAATAACATTTGTTATTGAGAGGGCCCTCCTGCGATTGGCTTGATGGTTCCGTAAGTGTGAAATGTCACTCCGTTATCGA
+
FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:14705:1000
ATGCCATAGATCATTGAGATTTCAAGGTTGGAAGGAGAGAAGTATATATGTTAATACCACGAAGAAATCTGGTGAAATTTGGTTGGGTTA
+
,FF,FFFF:F:FFFFFFFFFFFFF:FFFF:F:FF,FFFFFFFFFFF:FFFF,FFFFFFFFF,F::FFFFFFFFF,,F,F::,FFFFFFFF
@A00709:43:HYG25DSXX:1:1101:14814:1000
ATCGTAGGCAAAAGTTCCAACAAGATCTGTTGTCCCGCCGTCTGTCCCAAGGGGATTAACTTCACCCCCGCCCCAATTAAATTGCTCGCC
+
FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:14814:1000
CCTGTGCACAACTCCCTTTAACTAACCCCAGAATCATTATTAAGACTTCAACAACTAGCAAGTCCTATCTTGCCTGTCGGGAGTTACAGC
+
F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFF:FFFFFF
@A00709:43:HYG25DSXX:1:1101:15935:1000
CTCTTCCTTGTCGGCGGTGGAGAAGCAGAGGCAGAAAAGGTCGCGCTCGTAGGGGATGCCGTCCTCGATCGCCAGACGCTCGCTGGCGCG
+
FFFFF,FFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFF,FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:15935:1000
GACGCCGTTCGACCAGCGCCACGCCATGCGCAGCCCGCGGATCTTCGACGTCGTGGCGTCGTTCCCCAAGCCGGTGATCGCCATGATCAA
+
:FFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF,FFFFFFF:FFFFFFFFFFFF
@A00709:43:HYG25DSXX:1:1101:17960:1000
CCCGCACGCGGATGTTCGGATGGTTCCGCACGGCCTCGCTGAGGGCGGTCTGGATCACCAATCCGGTGGCGTCCTTGGCGTGGTAGATGC
+
FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:
@A00709:43:HYG25DSXX:1:1101:17960:1000
ATCATCGGCCTGGCGCCGCCGGAGGAAGGGGATTCGCCCGAGCTGCTGGCCGCGGATATCGAAGCCGCGGGCGCGGGCCTGTGCCGGACC
+
FFFF:FFFFFFFFFFFFFFFFF,FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFF
)"};
    CHECK_FILE_IDENTITY(data_path / "test3.fastq", expected_result, true);
  }
  SECTION("READFILE4.FASTQ") {
    std::string_view expected_result{R"()"};
    CHECK_FILE_IDENTITY(data_path / "test4.fastq", expected_result, true);
  }
  SECTION("READFILE5.FASTQ") {
    std::string_view expected_result{
      R"(@M03029:193:000000000-D2B6C:1:1101:15779:1330
CTTAGAAG
+
>AABBBDF
@M03029:193:000000000-D2B6C:1:1101:15821:1338
CTTAGAAG
+
ABCCCFFF
@M03029:193:000000000-D2B6C:1:1101:15389:1341
CTTAGAAG
+
>AABBFFF
@M03029:193:000000000-D2B6C:1:1101:15215:1344
CTTAGAAG
+
>AABBFBB
@M03029:193:000000000-D2B6C:1:1101:15519:1345
CTTAGAAG
+
>ABCCFFF
@M03029:193:000000000-D2B6C:1:1101:16240:1357
CTTAGAAG
+
3AAAADFF
@M03029:193:000000000-D2B6C:1:1101:15715:1360
CTTAGAAG
+
3AAAAF5B
@M03029:193:000000000-D2B6C:1:1101:15337:1360
CTTAGAAG
+
>1>A1131
@M03029:193:000000000-D2B6C:1:1101:15736:1362
CTTAGAAG
+
BBBCCFFF
@M03029:193:000000000-D2B6C:1:1101:15887:1362
CTTAGAAG
+
ABCBBFFF
@M03029:193:000000000-D2B6C:1:1101:16608:1365
CTTAGAAG
+
AABCBFFF
@M03029:193:000000000-D2B6C:1:1101:15106:1373
CTTAGAAG
+
>ABBBFFF
@M03029:193:000000000-D2B6C:1:1101:15404:1374
CTTAGAAG
+
3>AAABFF
@M03029:193:000000000-D2B6C:1:1101:15382:1375
CTTAGAAG
+
AABCCFFF
@M03029:193:000000000-D2B6C:1:1101:16235:1375
CTTAGAAG
+
>ABBAFFF
@M03029:193:000000000-D2B6C:1:1101:14878:1378
CTTAGAAG
+
1>>A11B1
@M03029:193:000000000-D2B6C:1:1101:14777:1378
CTTAGAAG
+
>ABCCFFF
@M03029:193:000000000-D2B6C:1:1101:16596:1379
CTTAGAAG
+
ABBBBFFF
@M03029:193:000000000-D2B6C:1:1101:16832:1379
CTTAAAAG
+
AABBAFFF
@M03029:193:000000000-D2B6C:1:1101:16907:1383
CTTAGAAG
+
AAABCFFF
)"};
    CHECK_FILE_IDENTITY(data_path / "test5.fastq", expected_result, true);
  }

  SECTION("READFILE6.FASTQ") {
    std::string_view expected_result{R"(@SEQ1
A
+
I
@SEQ2
N
+
!
@SEQ3
A
+
I
)"};
    CHECK_FILE_IDENTITY(data_path / "test6.fastq", expected_result, true);
  }

  SECTION("READFILE7.FASTQ") {
    std::string_view expected_result{R"(@SRR001666.1
GGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9IC
)"};
    CHECK_FILE_IDENTITY(data_path / "test7.fastq", expected_result, true);
  }

  SECTION("READFILE8.FASTQ") {
    std::string_view expected_result{R"(@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65
)"};
    CHECK_FILE_IDENTITY(data_path / "test8.fastq", expected_result, true);
  }

  SECTION("READFILE9.FASTQ") {
    std::string_view expected_result{R"(@MN00537:51:000H2K25G:1:11101:2213:1092
CTCCAGTCCTTACTCCCATATCTAACCTCTTACCCCTACNTCATAGGTANACATTTTAATGAAT
+
FFFFFFFFFFFFAFFFFFFFF=FFFFAFFFFFFF/AFFF#FFFFFFFFF#FFFFFFFF
@MN00537:51:000H2K25G:1:11101:2213:1092
CTCCAGTCCTTACTCCCATATCTAACCTCTTACCCCTACNTCATAGGTANACATTTTAATGAAT
+
FFFFFFFFFFFFAFFFFFFFF=FFFFAFFFFFFF/AFFF#FFFFFFFFF#FFFFFFFF
@MN00537:51:000H2K25G:1:11101:2213:1092
CTCCAGTCCTTACTCCCATATCTAACCTCTTACCCCTACNTCATAGGTANACATTTTAATGAAT
+
FFFFFFFFFFFFAFFFFFFFF=FFFFAFFFFFFF/AFFF#FFFFFFFFF#FFFFFFFF
@SRR001666.1
GGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACCGGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9ICIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9IC
)"};
    CHECK_FILE_IDENTITY(data_path / "test9.fastq", expected_result, true);
  }

  SECTION("READFILE10.FASTQ") {
    std::string_view expected_result{R"(@empSEQ

+

)"};
    CHECK_FILE_IDENTITY(data_path / "test10.fastq", expected_result, true);
  }
}

TEST_CASE("FASTA BASIC I/O") {
  SECTION("SINGLE RECORD") {
    FastaRecord record;
    std::istringstream iss{R"(>1
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG
)"};

    iss >> record;

    REQUIRE(record.name == "1");
    REQUIRE(
        record.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG");
  }

  SECTION("MUTIPLE RECORDS") {
    FastaRecord record1, record2, record3;
    std::istringstream iss{R"(>1
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG
>2
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAAC
>3
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCT
)"};

    iss >> record1 >> record2 >> record3;

    REQUIRE(record1.name == "1");
    REQUIRE(
        record1.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG");
    REQUIRE(record2.name == "2");
    REQUIRE(
        record2.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAAC");
    REQUIRE(record3.name == "3");
    REQUIRE(
        record3.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCT");
  }

  SECTION("CRLF") {
    FastaRecord record;
    std::istringstream iss{R"(>chr
C
A
A
G
T
C
)"};
    iss >> record;

    REQUIRE(record.name == "chr");
    REQUIRE(record.seq == "CAAGTC");
  }

  SECTION("EMBEDDED NEWLINE") {
    FastaRecord record1, record2, record3;
    std::istringstream iss{R"(>1
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG



>2
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA

ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAAC

>3
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCT
)"};

    iss >> record1 >> record2 >> record3;

    REQUIRE(record1.name == "1");
    REQUIRE(
        record1.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG");
    REQUIRE(record2.name == "2");
    REQUIRE(
        record2.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAAC");
    REQUIRE(record3.name == "3");
    REQUIRE(
        record3.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCT");
  }

  SECTION("MISMATCHED LINES") {
    FastaRecord record;
    std::istringstream iss{R"(>3
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCT
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG)"};

    iss >> record;

    REQUIRE(record.name == "3");
    REQUIRE(
        record.seq ==
        "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTCTAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTAACCC\
TAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCGCCCG\
CCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGACAACG\
CAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG");
  }
}

TEST_CASE("FASTA FILE I/O") {
  SECTION("READFILE1") {
    std::string_view expected_result{
      ">MCHU\n\
ADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID\
FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA\
DIDGDGQVNYEEFVQMMTAK*\n\
>gi|5524211|gb|AAD44166.1|\n\
LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQMSFWGATVITNLFSAIPYIGTNLV\
EWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDSDKIPFHPYYTIKDFLG\
LLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPNKLGGVLALFLSIVIL\
GLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIGQMASILYFSIILAFLPIAGX\
IENY\n"};
    CHECK_FILE_IDENTITY(data_path / "test1.fasta", expected_result, false);
  }

  SECTION("READFILE2") {
    std::string_view expected_result{
      ">1\n\
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG\n\
>2\n\
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACC\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAAC\n\
>3\n\
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC\
CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAA\
CCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCT\
AACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTA\
CTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTA\
ACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCG\
CCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGAC\
AACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGGCGCAGGCG\
ACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCT\n"};
    CHECK_FILE_IDENTITY(data_path / "test2.fasta", expected_result, false);
  }

  SECTION("READFILE3") {
    std::string_view expected_result{
      ">H59735\n\
AGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAAC\
GatgaagcggtgcttgcaccgtggattAGTGGCGAACGGGTGAGTAATACGTGAGTGACC\
TACCTTTGACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACCGGATACGACCAATCTC\
TGCATGGGGtGTTGGTgGAAAGCgttatggaGTGGTTTTAGATGGGCTCACGGCCTATCA\
GCTTGTTGGTGAGGTAATGGCTTACCAAGGCGACGACGGGTAGCCGGCCTGAGAGGGTGA\
CCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATA\
TTGCACAATGGGCGCAAGCCTGATGCAGCGACGCCGCGTGAGGGATGACGGCCTTCGGGT\
TGTAAACCTCTGTTAGCATCGAAGAagcgaaagTGACGGTAGGTGCAGAGAAAGC\n\
>T70875\n\
GAGTAATACATCGGAACGTACCCTGTTGTGGGGGATAACTAGTCGAAAGATTAGCTAATA\
CCGCATACGACCTGAGGGTGAAAGTgggggaccgcaaggcctcACGCAGCAGGAGCGGCC\
GATGTCTGATTAGCTAGTTGGTGGGGTAAAGGCCCACCAAGGCGACGATCAGTAGCTGGT\
CTGAGAGGACGATCAGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAG\
CAGTGGGGAATTTTGGACAATGGGGGCAACCCTGATCCAGCAATGCCGCGTGTGTGAAGA\
AGGCCTTCGGGTTGTAAAGCACTTTTGTCCGGAAAGAaatcgcgctggttaatacctggc\
gtggaTGACGGTACCGGAAGAATAAGCACC\n\
>F58095\n\
AGAGTTTGATCCTGGCTCAGAGCGAACGCTGGCGGCATGCTTAACACATGCAAGTCGCAC\
GggtggtttcggccatcAGTGGCGGACGGGTGAGTAACGCGTAGGAACGTGTCCAGAGGT\
GGGGGACAACCCCGGGAAACTGGGGCTAATACCGCATGGGGGCTGAGGCCCAAAGCcgaa\
agGCGCCTTTGGAGCGGCCTGCGTCCGATTAGGTAGTTGGTGGGGTAAAGGCCTACCAAG\
CCTGCGATCGGTAGCTGGTCTGAGAGGACGACCAGCCACACTGGGACTGAGACACGGCCC\
AGACTCCTACGGGAGGCAGCAGTGGGGAATATTGGACAATGGGCGAAAGCCTGATCCAGC\
AATGCCGCGTGGGTGAAGAAGGTCTTCGGATCGTAAAGCCCTTTCGACGGGGACGAtgaT\
GACGGTACCCGTAGAAGAAGCCCC\n\
>T70854\n\
TGGCGGCAGGCCTAACACATGCAAGTCGAGCGgatgacgggagcttgctccttgattcAG\
CGGCGGACGGGTGAGTAATGCCTAGGAATCTGCCTGGTAGTGGGGGACAACGTTTCGAAA\
GGAACGCTAATACCGCATACGTCCTACGGGAGAAAGCaggggaccttcgggccttGCGCT\
ATCAGATGAGCCTAGGTCGGATTAGCTAGTTGGTGGGGTAATGGCTCACCAAGGCGACGA\
TCCGTAACTGGTCTGAGAGGATGATCAGTCACACTGGAACTGAGACACGGTCCAGACTCC\
TACGGGAGGCAGCAGTGGGGAATATTGGACAATGGGCGAAAGCCTGATCCAGCCATGCCG\
CGTGTGTGAAGAAGGTCTTCGGATTGTAAAGCACTTTAAGTTGGGAGGAagggcagtaag\
ctaataccttgctgtttTGACGTTACCGACAGAATAAGC\n\
>F62024\n\
AGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAAC\
GatgaagcctttcggggtggattAGTGGCGAACGGGTGAGTAACACGTGGGCAATCTGCC\
CTTCACTCTGGGACAAGCCCTGGAAACGGGGTCTAATACCGGATAACACTCTGTCCCGCA\
TGGGACGGGGTtAAAAGCtccgGCGGTGAAGGATGAGCCCGCGGCCTATCAGCTTGTTGG\
TGGGGTAATGGCCTACCAAGGCGACGACGGGTAGCCGGCCTGAGAGGGCGACCGGCCACA\
CTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAAT\
GGGCGAAAGCCTGATGCAGCGACGCCGCGTGAGGGATGACGGCCTTCGGGTTGTAAACCT\
CTTTCAGCAGGGAAGAagcgaaagTGACGGTACCTGCAGAAGAAGCGCC\n\
>H59895\n\
AAGTCGAACGgtgaaagagagcttagctctctggatcAGTGGCGAACGGGTGAGTAACAC\
GTGAGCAATCTGCCCCTGACTCTGGGATAACAGCTGGAAACAGCTGCTAATACCGGATAC\
GAGTTGCGAAGGCATCTTCaGCAGCTgGAAAGAattTCGGTCAGGGATGAGCTCGCGGCC\
TATCAGCTTGTTGGTGAGGTAATGGCTCACCAAGGCGTCGACGGGTAGCCGGCCTGAGAG\
GGTGACCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGG\
GAATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGCGTGAGGGACGACGGCCTT\
CGGGTTGTAAACCTCTTTTAGCAAGGAAGAagcgaaagTGACGGTACTTGCAGAAAAAGC\
GCC\n\
>F57728\n\
TTAGTGGCGAACGGGTGAGTAACGCGTAATCAACCTGCCCTTCAGAGGGGGACAACAGTT\
GGAAACGACTGCTAATACCGCATACGATCTAaTCTCGGCATCGAGGaTAGATGAAAGGtg\
gcctctacatgtaagctaTCACTGAAGGAGGGGATTGCGTCTGATTAGCTAGTTGGAGGG\
GTAACGGCCCACCAAGGCGATGATCAGTAGCCGGTCTGAGAGGATGAACGGCCACATTGG\
GACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATCTTCCGCAATGGAC\
GAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGACGGCCTTCGGGTTGTAAAGCTCTGT\
TAATCGGGACGAaaggccttcttgcgaatagtgagaaggatTGACGGTACCGGAATAGAA\
AGCCACGC\n\
>M10734\n\
GCTGACGGCGTGCTTAACACATGCAAGTCGAACGggatccattagcgcttttgtgttttt\
ggtgagAGTGGCGAACGGGTGAGTAACACGTGAGTAACCTGCCCTTTTCTTTGGGATAAG\
CCTGGGAAACTGGGTCTAATACTGGATGTTcCGGCTTCCTCGCATGGGGTTGTTGgGAAA\
GGttttttCTGGATTGGGATGGGCTCGCGGCTTATCAGCTTGTTGGTGGGGTGATGGCTT\
ACCAAGGCTTTGACGGGTAGCCGGCCTGAGAGGGTGGTCGGTCACACTGGGACTGAGATA\
CGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGGATATTGCACAATGGACGGAAGTCTGA\
TGCAGCGACGTCGTGTGGGGGATGAAGGCCTTCGGGTTGTAAACTCC\n\
>T71041\n\
CGCTGGCGGCAGGCTTAACACATGCAAGTCGAACGatgaagtctagcttgctagacggat\
tAGTGGCGAACGGGTGAGTAATGCTTAGGAATCTGCCTATTAGTGGGGGATAACGTAGGG\
AAACTTACGCTAATACCGCATACGTCTTACGAGAGAAAGGgggcttttagctcTCGCTAA\
TAGATGAGCCTAAGTCGGATTAGCTAGTTGGTGGGGTAAAGGCCTACCAAGGCGACGATC\
TGTAGCTGGTCTGAGAGGATGATCAGCCACACTGGGACTGAGACACGGCCCAGACTCCTA\
CGGGAGGCAGCAGTGGGGAATATTGGACAATGGGCGAAAGCCTGATCCAGCCATGCCGCG\
TGTGTGAAGAAGGCCTTTTGGTTGTAAAGCACTTTAAGTGGGGAGGAaaagcttgtggtt\
aatacccacaagcccTGACGTTACCCA\n\
>M6161O\n\
TGGCGGTGGCCTAACACATGCAAGTCGAACGgatccttcgggattAGTGGCGGACGGGTG\
AGTAACACGTGGGAACGTGCCCTTTGGTTCGGAACAACTCAGGGAAACTTGAGCTAATAC\
CGGATGTGCCCTTCGGGGGAAAGAtttaTCGCCATTGGAGCGGCCCGCGTCTGATTAGCT\
AGTTGGTGGGGTAAAGGCTCACCAAGGCGACGATCAGTAGCTGGTCTGAGAGGATGATCA\
GCCACATTGGGACTGAGACACGGCCCAAACTCCTACGGGAGGCAGCAGTGGGGAATCTTG\
CGCAATGGGCGAAAGCCTGACGCAGCCATGCCGCGTGAATGATGAAGGTCTTAGGATTGT\
AAAATTCTTTCACCGGGGACGAtaaTGACGGTACCCGGAGAAGAAGCCCC\n"};
    CHECK_FILE_IDENTITY(data_path / "test3.fasta", expected_result, false);
  }

  SECTION("READFILE4") {
    std::string_view expected_result{
      ">SEQUENCE_1\n\
MTEITAAMVKELRESTGAGMMDCKNALSETNGDFDKAVQLLREKGLGKAAKKADRLAAEG\
LVSVKVSDDFTIAAMRPSYLSYEDLDMTFVENEYKALVAELEKENEERRRLKDPNKPEHK\
IPQFASRKQLSDAILKEAEEKIKEELKAQGKPEKIWDNIIPGKMNSFIADNSQLDSKLTL\
MGQFYVMDDKKTVEQVIAEKEKEFGGKIKIVEFICFEVGEGLEKKTEDFAAEVAAQL\n\
>SEQUENCE_2\n\
SATVSEINSETDFVAKNDQFIALTKDTTAHIQSNSLQSVEELHSSTINGVKFEEYLKSQI\
ATIGENLVVRRFATLKAGANGVVNGYIHTNGRVGVVIAAACDSAEVASKSRDLLRQICMH\n"};
    CHECK_FILE_IDENTITY(data_path / "test4.fasta", expected_result, false);
  }

  SECTION("READFILE5") {
    std::string_view expected_result{
      ">gi|186681228|ref|YP_001864424.1|\n\
MNSERSDVTLYQPFLDYAIAYMRSRLDLEPYPIPTGFESNSAVVGKGKNQEEVVTTSYAFQTAKLRQIRA\
AHVQGGNSLQVLNFVIFPHLNYDLPFFGADLVTLPGGHLIALDMQPLFRDDSAYQAKYTEPILPIFHAHQ\
QHLSWGGDFPEEAQPFFSPAFLWTRPQETAVVETQVFAAFKDYLKAYLDFVEQAEAVTDSQNLVAIKQAQ\
LRYLRYRAEKDPARGMFKRFYGAEWTEEYIHGFLFDLERKLTVVK\n"};
    CHECK_FILE_IDENTITY(data_path / "test5.fasta", expected_result, false);
  }

  SECTION("READFILE6") {
    std::string_view expected_result{
      ">NM_012514\n\
CGCTGGTGCAACTCGAAGACCTATCTCCTTCCCGGGGGGGCTTCTCCGGCATTTAGGCCT\
CGGCGTTTGGAAGTACGGAGGTTTTTCTCGGAAGAAAGTTCACTGGAAGTGGAAGAAATG\
GATTTATCTGCTGTTCGAATTCAAGAAGTACAAAATGTCCTTCATGCTATGCAGAAAATC\
TTGGAGTGTCCAATCTGTTTGGAACTGATCAAAGAACCGGTTTCCACACAGTGCGACCAC\
ATATTTTGCAAATTTTGTATGCTGAAACTCCTTAACCAGAAGAAAGGACCTTCCCAGTGT\
CCTTTGTGTAAGAATGAGATAACCAAAAGGAGCCTACAAGGAAGTGCAAGG\n\
>NM_012515\n\
TGTGGATCTTTCCAGAACAGCAGTTGCAATCACTATGTCTCAATCCTGGGTACCCGCCGT\
GGGCCTCACTCTGGTGCCCAGCCTGGGGGGCTTCATGGGAGCCTACTTTGTGCGTGGTGA\
GGGCCTCCGCTGGTATGCTAGCTTGCAGAAACCCTCCTGGCATCCGCCTCGCTGGACACT\
CGCTCCCATCTGGGGCACACTGTATTCGGCCATGGGGTATGGCTCCTACATAATCTGGAA\
AGAGCTGGGAGGTTTCACAGAGGAGGCTATGGTTCCCTTGGGTCTCTACACTGGTCAGCT\n"};
    CHECK_FILE_IDENTITY(data_path / "test6.fasta", expected_result, false);
  }

  SECTION("READFILE7") {
    std::string_view expected_result{""};
    CHECK_FILE_IDENTITY(data_path / "test7.fasta", expected_result, false);
  }

  SECTION("READFILE8") {
    std::string_view expected_result{
      ">2ptl_\n\
VTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKDNGEYTVDVAD\
KGYTLNIKFAAAAAVTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKD\
NGEYTVDVADKGYTLNIKFA\n\
>2ptl_\n\
VTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKDNGEYTVDVAD\
KGYTLNIKFAAAAAVTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKD\
NGEYTVDVADKGYTLNIKFA\n\
>2ptl_\n\
VTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKDNGEYTVDVAD\
KGYTLNIKFAAAAAVTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKD\
NGEYTVDVADKGYTLNIKFA\n\
>2ptl_\n\
VTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKDNGEYTVDVAD\
KGYTLNIKFAAAAAVTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKD\
NGEYTVDVADKGYTLNIKFA\n\
>2ptl_\n\
VTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKDNGEYTVDVAD\
KGYTLNIKFAAAAAVTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKD\
NGEYTVDVADKGYTLNIKFA\n\
>2ptl_\n\
VTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKDNGEYTVDVAD\
KGYTLNIKFAAAAAVTIKANLIFANGSTQTAEFKGTFEKATSEAYAYADTLKKD\
NGEYTVDVADKGYTLNIKFA\n"};
    CHECK_FILE_IDENTITY(data_path / "test8.fasta", expected_result, false);
  }

  SECTION("READFILE9") {
    std::string_view expected_result{
      ">BBP_PIEBR\n\
NVYHDGACPEVKPVDNFDWSNYHGKWWEVAKYPNSVEKYGKCGWAEYTPEGKSVKVSNYHVIHGKEYFIEGTAYPVGDSKIGKIYHKLTYGGVTKENVFNVLSTDNKNYIIGYYCKYDEDKKGHQDFVWVLSRSKVLTGEAKTAVENYLI\
GSPVVDSQKLVYSDFSEAACKVN\n"};
    CHECK_FILE_IDENTITY(data_path / "test9.fasta", expected_result, false);
  }
  SECTION("READFILE10") {
    std::string_view expected_result{">gi|129295|sp|P01013|OVAX_CHICK\n\n"};
    CHECK_FILE_IDENTITY(data_path / "test10.fasta", expected_result, false);
  }

  SECTION("Single record") {
    std::istringstream iss{R"(@SRR001666.1
GGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9IC
)"};

    auto r = std::ranges::istream_view<FastqRecord<>>(iss);
    auto record = *r.begin();

    REQUIRE(record.name == "SRR001666.1");
    REQUIRE(record.seq == "GGGTGATGGCCGCTGCCGATGGCGTCAAATCCCACC");
    REQUIRE(record.qual == "IIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IG9IC");
  }
}
