name: pull-request-check

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: jhhlab/biovoltron-ci-env:20230914
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build Biovoltron
      run: |
        mkdir build
        cd build
        cmake .. -DGCOV=ON -DBIOVOLTRON_DOC=ON
        make -j
    - name: Run unit-test
      run: |
        cd build
        ./tests/biovoltron-test
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: ./build/doc/doxygen/html
